export const userConstants = {
    LOGIN_PENDING: 'USERS_LOGIN_PENDING',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_ERROR: 'USERS_LOGIN_ERROR',

    GET_USERS: "GET_USERS",

    LOGOUT : "USER_LOGOUT",
    
    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE'
}